<?php

namespace AppBundle\Entity;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommentsList($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM AppBundle:Comments c WHERE c.task = :id ")
                        ->setParameter("id", $id);
        return $query->getArrayResult();
    }
}
